# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Beforeget-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Beforeget-iOS
  pod 'SwiftGen', '~> 6.0'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Then'
  pod 'lottie-ios'
  pod 'Moya', '~> 14.0'
  pod 'Kingfisher', '~> 6.0'
  pod 'IQKeyboardManagerSwift', '6.3.0'

end
